name: 'WIPAC Dev Py Versions'
description: 'GitHub Action Package for Generating a Build Matrix of Supported Python Versions for a Package'

# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'

outputs:
  matrix:
    description: "List of Supported Python Versions"
    value: ${{ steps.gather-py3-versions.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - id: gather-py3-versions
      run: |
          pys=`grep -P "python_requires = >=3.\d+,( )*<3.\d+" -oh setup.cfg` # exits if missing
          minmin_maxmax=`echo "$pys" | sed 's/[^0-9]/ /g'` # ex: 3 6 3 11
          echo $minmin_maxmax
          if [ -z "$minmin_maxmax" ]; then
            echo "could not retrieve 'python_requires' from 'setup.cfg'"
            exit 1
          fi
          IFS=', ' read -r -a array <<< "$minmin_maxmax"
          min_thru_max_series=$(for i in `seq ${array[1]} $((array[3]-1))`; do printf "'3.$i',"; done | rev | cut -c 2- | rev)
          echo "::set-output name=matrix::$(echo $min_thru_max_series)"
          echo $min_thru_max_series
      shell: bash
