name: 'WIPAC Dev Py Versions'
description: 'GitHub Action Package for Generating a Build Matrix of Supported Python Versions for a Package'

# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'

outputs:
  matrix:
    description: "List of Supported Python Versions"
    value: ${{ steps.gather-py-versions.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - id: gather-py-versions
      run: |
          pip3 install wipac-dev-tools[semvar]

          SEMVAR_RANGE=$(grep "python_requires =" -h setup.cfg | awk -F 'python_requires =' '{print $2}')

          MIN_THRU_MAX_SERIES=$(python -c '
          import os
          from wipac_dev_tools import semvar_parser_tools
          top_python = semvar_parser_tools.get_latest_py3_release()
          all_matches = semvar_parser_tools.list_all_majmin_versions(
            major=top_python[0],
            semvar_range=os.environ["SEMVAR_RANGE"],
            max_minor=top_python[1],
          )
          print(" ".join(f"{v[0]}.{v[1]}" for v in all_matches))
          ')

          echo $MIN_THRU_MAX_SERIES
      shell: bash
